name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 35.174.114.81
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            cd ~/ci-cd-demo3
            git pull
            ./mvnw clean package
            nohup java -jar target/demo-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
